version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - server
      - ui

  server:
    build:
      context: app/server
      dockerfile: Dockerfile
    volumes:
      - ./app/server:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .

  ui:
    build:
      context: app/ui
      dockerfile: Dockerfile
    volumes:
      - './app/ui:/app:cached'
      - './app/ui/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=production
